### ISSUE TITLE
unRAID Template

### ISSUE THREAD

**Issue by jrdnlc** [zaggash/docker-filerun#1]
Anyone have a template to run this in unRAID? I'm trying to create a template myself but having a hard time finding the docker run command.

Would be greatly appreciated if you can share the template if you have it.

Thank you!

**Comment by zaggash** [comment]
This is a personnal image, not a linuxserver.io.
I do not use unraid myself.
I can help you if you describe you needs.

I added a readme, tell me if it helps

**Comment by zaggash** [comment]
No news, I'm closing it.
Reopen if needed.
