### ISSUE TITLE
No access from android app

### ISSUE THREAD

**Issue by sprnza** [zaggash/docker-filerun#3]
Hi there!
Thanks for the image! 
I've stumbled upon a wierd issue. OAuth access via Android Filerun app doesn't work for some reason. It does work with the "official" image, but there are no an option to set UID/GUID variables though. Where could I find related logs in the container?

**Comment by zaggash** [comment]
I'll have to take a look and check the differances.
I'm out, afk until next week.

**Comment by sprnza** [comment]
Seems like I've found the issue. Based on [this](https://feedback.filerun.com/communities/1/topics/264-android-app-stuck-on-loading-after-sign-in), [this ](https://feedback.filerun.com/communities/1/topics/187-provide-nginx-config-example)and [this](https://www.nginx.com/resources/wiki/start/topics/examples/phpfcgi/) it was a nginx misconfiguration. So the missing part is:

```
    location ~ [^/]\.php(/|$) {

                fastcgi_split_path_info ^(.+?\.php)(/.*)$;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_param PATH_INFO $fastcgi_path_info;
                fastcgi_param HTTPS on;

                #Avoid sending the security headers twice
                fastcgi_param modHeadersAvailable true;
                fastcgi_param front_controller_active true;
                fastcgi_intercept_errors on;
                fastcgi_request_buffering off;

                fastcgi_pass unix:/run/php/php7.0-fpm.sock;
               fastcgi_index index.php;
               include /etc/nginx/fastcgi_params;
        }

```

**Comment by zaggash** [comment]
Its been a while since I updated this image.
I'll check your change and add update the image.

I have to automate the upgrade.

Stay tuned.

**Comment by zaggash** [comment]
Fixed with https://github.com/zaggash/docker-filerun/pull/4
