### ISSUE TITLE
Error 500 after first start

### ISSUE THREAD

**Issue by beemeeup** [zaggash/docker-filerun#7]
hen I look at log/nginx/error.log is can see the following lines:

2020/06/30 08:20:59 [error] 282#282: *2 FastCGI sent in stderr: "PHP message: PHP Fatal error:  <br/>The file <b>/config/www/filerun/index.php</b> was encoded with the Encoder for PHP 7.1 and can only run on PHP 7.1 or later.<br/> If you are the administrator of this site then please upgrade to PHP 7.1 or later and install the corresponding ionCube Loader. in Unknown on line 0" while reading response header from upstream, client: 172.16.20.122, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "172.16.10.82:83", referrer: "http://172.16.10.82:9000/"

How can this be fixed?
Thanks

**Comment by zaggash** [comment]
Hi @beemeeup ,

I'll have a look at it today.

**Comment by zaggash** [comment]
Fixed with https://github.com/zaggash/docker-filerun/commit/f9651bf82e84a0158bf187fb04457dc916b5f716

I'm closing, feel free to raise another issue if something goes wrong!

**Comment by beemeeup** [comment]
Thx
